### ISSUE TITLE
Symbol's function definition is void: global-git-gutter+-mode

### ISSUE THREAD

**Issue by firedev** [nonsequitur/git-gutter-plus#14]
Hi,

I suggest to change docs to something like the following to prevent function definition is void error. Thanks.

```lisp
(add-hook 'after-init-hook 'global-git-gutter+-mode)
```
I am using Emacs 25.

**Comment by nonsequitur** [comment]
I'll close this for now. This is probably a bug in Emacs 25 that will be fixed before the final release.
