### ISSUE TITLE
git-gutter+ has error in sh-mode sometimes

### ISSUE THREAD

**Issue by stardiviner** [nonsequitur/git-gutter-plus#16]
```
(wrong-number-of-arguments nil 0)
  signal(wrong-number-of-arguments (nil 0))
  git-gutter+-process-diff("/home/stardiviner/scripts/autostart/play_video.sh")
  git-gutter+-refresh()
  run-hooks(after-save-hook)
  basic-save-buffer()
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```

I open the file with Emacs server mode enabled, and open it with `emacsclient`.
I got this error backtrack sometimes when I open a bash script file, and do some modifcations, and try to save this file. Then I got this error.

And I have not meet this error in other formats. and not in a opened new file.

My Emacs version: "GNU Emacs 25.0.50.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.4)\n of 2014-11-03 on dark"

**Comment by nonsequitur** [comment]
Please try to load the uncompiled source by adding to following to your config:
`(load "path/to/git-gutter+.el")`

That should give a more detailed backtrace. Right now, I can't see which function call is failing.

**Comment by stardiviner** [comment]
After load that file, I got this output from shell,
```*ERROR*: Wrong number of arguments: nil, 0```
And have a shell command alias
```alias e=emacsclient -c```

**Comment by nonsequitur** [comment]
So you `(load "path/to/git-gutter+.el")` to your .emacs and now Emacs fails starting up?

Try running Emacs with the option `--debug-init` to get a full backtrace.

**Comment by stardiviner** [comment]
No, I mean after added that line into my `.emacs`, I can run Emacs, but my alias `alias e=emacsclient -c` will fail at first time when I open a file `e filename.sh`, and shows that error message in shell, but the second time I can open the file successfully without any error. This is where I find it weird.

(Sorry I have not declare my situation clearly at first)

**Comment by nonsequitur** [comment]
1. Does the same error occur when you open the file by `find-file` right after starting Emacs?

2. Could you check if the error persists if you run your config in Emacs 24 instead of 25?

**Comment by stardiviner** [comment]
1. Never have error when I use `find-file`
2. I'm using Arch Linux, I need to google it how to install Emacs 24 on Arch. (I will update later)

**Comment by nonsequitur** [comment]
It's probably related to symlinks. Here's the [relevant issue](https://github.com/nonsequitur/git-gutter-plus/issues/20#issuecomment-108865754).
