### ISSUE TITLE
git-gutter+-stage-hunks doesn't work across Tramp

### ISSUE THREAD

**Issue by domq** [nonsequitur/git-gutter-plus#17]
Steps to reproduce:

* Open remote file w/ Tramp
* Select region
* M-x git-gutter+-stage-hunks

Result:
```
Error staging hunks:
fatal: --cached outside a repository
```

Platform details:
Emacs for Mac OS X (from http://emacsformacosx.com/), emacs-version 24.4.50.1

**Comment by domq** [comment]
AIUI, the trouble is that `call-process-region` doesn't work through tramp. The org-mode folks [ran into the same problem before](http://orgmode.org/w/?p=org-mode.git;a=commitdiff_plain;h=2056d7d419aabfc9a5fd59674f66e58862f14e32).

**Comment by domq** [comment]
Running the following code (cobbled together from the Git history over at https://github.com/emacsmirror/tramp) gets the hunk feature working remotely. Note that [`tramp-sh-handle-call-process-region` was deleted in December 2012](https://github.com/emacsmirror/tramp/commit/ece1338c5e9eaf2c9c86722e668d1ce1603a8cb2) for some reason.

```emacs-lisp
(defun tramp-sh-handle-call-process-region
    (start end program &optional delete buffer display &rest args)
  "Like `call-process-region' for Tramp files."
  (let ((tmpfile (tramp-compat-make-temp-file "")))
    (write-region start end tmpfile)
    (when delete (delete-region start end))
    (unwind-protect
        (apply 'process-file program tmpfile buffer display args)
      (delete-file tmpfile))))

(defadvice call-process-region
  (around tramp-advice-call-process-region activate)
  "Invoke `tramp-sh-handle-call-process-region' for Tramp files."
  (if (eq (tramp-find-foreign-file-name-handler default-directory)
          'tramp-sh-file-name-handler)
      (setq ad-return-value
            (apply 'tramp-sh-handle-call-process-region (ad-get-args 0)))
    ad-do-it))

```

**Comment by domq** [comment]
Pull request #18 is a cleaned-up version of the above.

**Comment by nonsequitur** [comment]
[Commited](https://github.com/nonsequitur/git-gutter-plus/commits/master)
