### ISSUE TITLE
git-commit-mode dependency is unavailable

### ISSUE THREAD

**Issue by jacktasia** [nonsequitur/git-gutter-plus#22]
Howdy,

After doing a `rm -rf ~/.emacs.d` I am now getting:

> Package `git-commit-mode-0.14' is unavailable

when I try to `package-install` `git-gutter+`. 

It seems like `git-commit-mode` is now (part of?) `magit`?

**Comment by nonsequitur** [comment]
[Fixed.](https://github.com/nonsequitur/git-gutter-plus/commit/dd23f0c72c9a312f573f874b7261cefc83bdc904)
