### ISSUE TITLE
injects git warnings into commit messages

### ISSUE THREAD

**Issue by ensc** [nonsequitur/git-gutter-plus#26]
When git prints non-criticial warnings or error messages, these are injected into commit messages.

E.g.

```bash
# prepare git repository
mkdir /tmp/XXX
cd /tmp/XXX
git init

# cause a warning
echo /non-existing > .git/objects/info/alternates

# do some work
echo foo > test
git add test
git commit -m 'initial checkin' test
```

Now, open the `/tmp/XXX/test` file in emacs, change it, do `git-gutter+-stage-hunks` and `git-gutter+-commit`.

The resulting commit message will contain the

    error: object directory /non-existing does not exist; check .git/objects/info/alternates.

warning which is sometimes added to the code too.

**Comment by nonsequitur** [comment]
[Fixed](https://github.com/nonsequitur/git-gutter-plus/commit/087b799ef1944e0182d12335f363d41d25a3944c). Thanks for the report! :cop:
