### ISSUE TITLE
git-gutter+-show-hunk not updating when switching between hunks

### ISSUE THREAD

**Issue by el-ethan** [nonsequitur/git-gutter-plus#28]
I have switched to git-gutter+ from git-gutter, and I am very happy with it for the most part, but the git-gutter+-show-hunk diff is not updating when I call git-gutter+-previous-hunk and git-gutter+-next-hunk. The point does move to different hunks, but the diff displays for the hunk when  git-gutter+-show-hunk was first called. According to the documentation this should update the diff, so I am wondering if this is a bug, or something I need to configure differently. This feature does work for me in git-gutter, and I was hoping for similar functionality with this mode. Thank you!

**Comment by nonsequitur** [comment]
Yes, that was a bug. Thanks for the report! :cop:
